version: '3'

# Named volumes
volumes:
  test-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: test-mysql
    volumes:
      - test-mysql-data:/var/lib/mysql
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    networks:
      - local_network

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.2-nginx
    container_name: test-app
    volumes:
      - .:/var/www/app
    ports:
      - "${APP_PORT:-80}:8080"
    networks:
      - local_network
      - admin_app_network


networks:
    local_network:
      driver: bridge
    admin_app_network:
      driver: bridge
      external: true
